// SPDX-License-Identifier: GPL-2.0-only OR MIT
// Generated by tools/m3-gpu/emit-kernel-schema.py; owned configuration, no firmware code.
pub(crate) const QUEUE: usize = 31;
pub(crate) const QUEUE_STATE: usize = 32;
pub(crate) const STAMP: usize = 35;
pub(crate) const FW_STAMP: usize = 36;
pub(crate) const EVENT: usize = 29;
pub(crate) const COMMAND: usize = 42;
pub(crate) const MICROSEQUENCE: usize = 44;
pub(crate) const POOL: usize = 25;
pub(crate) const EXPECTED_STAMP: usize = 3238002944;
pub(crate) const OBJECTS: &[(usize, bool, u32, bool, &[u8])] = &[
    (16384, true, 1, false, &[]), // unk_iova_page
    (4194304, false, 1, false, &[]), // UMA pool 0
    (4194304, false, 1, false, &[]), // UMA pool 1
    (4194304, false, 1, false, &[]), // UMA pool 2
    (4194304, false, 1, false, &[]), // UMA pool 3
    (4194304, false, 1, false, &[]), // UMA pool 4
    (4194304, false, 1, false, &[]), // UMA pool 5
    (4194304, false, 1, false, &[]), // UMA pool 6
    (4194304, false, 1, false, &[]), // UMA pool 7
    (4194304, false, 1, false, &[]), // UMA pool 8
    (4194304, false, 1, false, &[]), // UMA pool 9
    (4194304, false, 1, false, &[]), // UMA pool 10
    (4194304, false, 1, false, &[]), // UMA pool 11
    (4194304, false, 1, false, &[]), // UMA pool 12
    (4194304, false, 1, false, &[]), // UMA pool 13
    (4194304, false, 1, false, &[]), // UMA pool 14
    (4194304, false, 1, false, &[]), // UMA pool 15
    (4194304, false, 1, false, &[]), // UMA pool 16
    (4194304, false, 1, false, &[]), // UMA pool 17
    (4194304, false, 1, false, &[]), // UMA pool 18
    (4194304, false, 1, false, &[]), // UMA pool 19
    (4194304, false, 1, false, &[]), // UMA pool 20
    (4194304, false, 1, false, &[]), // UMA pool 21
    (4194304, false, 1, false, &[]), // UMA pool page list
    (4096, false, 1, false, &[]), // UMA pool list
    (132, true, 0, false, &[]), // UMA pool manager
    (64, true, 0, false, &[]), // UMA pool manager counter?
    (64, false, 0, false, &[]), // GPUContextData
    (264, false, 0, false, &[]), // EventControl
    (4, false, 0, false, &[]), // event_count
    (24, false, 0, false, &[]), // JobList
    (180, false, 0, false, &[]), // CommandQueueInfo
    (96, false, 0, false, &[]), // CommandQueuePointers
    (10240, false, 0, false, &[]), // GPUWorkQueue.RB
    (262144, true, 0, false, &[]), // GPUWorkQueue.gpu_buf
    (4, true, 0, false, &[]), // CL stamp 1
    (4, true, 0, false, &[]), // CL stamp 2
    (8, true, 0, false, &[]), // CL timestamp start
    (8, true, 0, false, &[]), // CL timestamp end
    (8, false, 0, false, &[]), // CL user timestamp start
    (8, false, 0, false, &[]), // CL user timestamp end
    (65536, false, 1, false, &[]), // Deflake 1
    (2195, true, 0, true, &[]), // WorkCommandCP
    (65536, true, 0, false, &[]), // unk_ptr_857
    (4096, false, 0, false, &[]), // GPUMicroSequence
    (65536, true, 0, false, &[]), // g15_ptr_18
    (65536, true, 0, false, &[]), // g15_gptr_28
    (65536, true, 0, false, &[]), // g15_gptr_30
    (65536, true, 0, false, &[]), // g15_gptr_38
    (65536, true, 0, false, &[]), // g15_gptr_40
];
pub(crate) const RELOCS: &[(usize, usize, usize, u64, u32, u64)] = &[
];
pub(crate) const CONTEXT_PATCHES: &[(usize, usize)] = &[
];
pub(crate) const VAS: &[u64] = &[
    0x2ffffff8000,
    0x10080000000,
    0x10080408000,
    0x10080810000,
    0x10080c18000,
    0x10081020000,
    0x10081428000,
    0x10081830000,
    0x10081c38000,
    0x10082040000,
    0x10082448000,
    0x10082850000,
    0x10082c58000,
    0x10083060000,
    0x10083468000,
    0x10083870000,
    0x10083c78000,
    0x10084080000,
    0x10084488000,
    0x10084890000,
    0x10084c98000,
    0x100850a0000,
    0x100854a8000,
    0x100858b0000,
    0x10085cbb000,
    0xfffffc2070003f7c,
    0xfffffc207000bfc0,
    0xfffffc20003bbfc0,
    0xfffffc20003ffef8,
    0xfffffc2000443ffc,
    0xfffffc204062ffe8,
    0xfffffc2000487f4c,
    0xfffffc2040673fa0,
    0xfffffc20004c9800,
    0xfffffc2070010000,
    0xfffffc2070057ffc,
    0xfffffc207005fffc,
    0xfffffc2070067ff8,
    0xfffffc207006fff8,
    0xfffffc2071003ff8,
    0xfffffc207100bff8,
    0x10085cc0000,
    0xfffffc2070077760,
    0xfffffc207007c000,
    0xfffffc200050f000,
    0xfffffc2070090000,
    0xfffffc20700a4000,
    0xfffffc20700b8000,
    0xfffffc20700cc000,
    0xfffffc20700e0000,
];

// Queue fields come from live owners; other empty entries are zeroed storage.
pub(crate) const ENCODED_OBJECTS: &[usize] = &[23,24,25,26,27,28,29,30,31,32,33,35,41,42,44];
