# SPDX-License-Identifier: GPL-2.0-only OR MIT
obj-m += m3_dcp_rtkit.o
m3_dcp_rtkit-y := m3_dcp_rtkit_main.o m3_dcp_bridge.o m3_dcp_native.o m3_dcp_kms.o m3_dcp_parser.o
obj-m += m3_dcp_regs.o
obj-m += m3_dcp_hold.o
obj-m += m3_dcp_vote.o
obj-m += m3_dcp_ptd_vote.o
obj-m += m3_dcp_clock_restore.o
obj-m += m3_dcp_query.o
obj-m += m3_dcpext_regs.o
obj-m += m3_dcpext_power.o
obj-m += m3_dcpext_dma.o
obj-m += m3_dcpext_rtkit.o
m3_dcpext_rtkit-y := m3_dcpext_rtkit_main.o m3_dcpext_rpc.o m3_dcpext_native.o m3_dcpext_modes.o m3_dcpext_kms.o m3_dcpext_connector.o
obj-m += m3_hdmi_phy.o
obj-m += m3_hdmi_bridge.o
obj-m += m3_hdmi_xbar.o
obj-m += m3_typec_probe.o
obj-m += m3_usbc_ptd_vote.o
obj-m += m3_dcpext_secondary_power.o
obj-m += m3_dcpext_secondary.o
m3_dcpext_secondary-y := m3_dcpext_secondary_main.o m3_dcpext_rpc.o m3_dcpext_native.o m3_dcpext_modes.o m3_dcpext_kms.o m3_dcpext_connector.o
obj-m += m3_usbc_phy.o

obj-m += m3_dcpext_audio_pcm.o
